import { mkdirSync, writeFileSync } from "node:fs";

import type { MapStation, StationsMapData } from "types/api";
import { fetchGraphQL } from "utils/fetcher";
import { cleanStationName } from "utils/species";

type GraphQLStationNode = {
  id: string;
  name: string | null;
  coords: { lat: number; lon: number } | null;
  latestDetectionAt: string | null;
};

type GraphQLStationsResponse = {
  data?: {
    stations?: {
      pageInfo: { hasNextPage: boolean; endCursor: string | null };
      nodes: GraphQLStationNode[];
    };
  };
};

const PAGE_SIZE = 5000;
const MAX_PAGES = 10;
const DETECTION_PERIOD_YEARS = 20;

const DATA_DIRECTORY = "public/data";
const DATA_FILE = `${DATA_DIRECTORY}/stations.json`;
const CONSTANT_FILE = "constants/stations.ts";

// Round coordinates to 4 decimals (~11 m accuracy), enough for a map pin
const roundCoordinate = (value: number) => Math.round(value * 10000) / 10000;

// Fetch every public station from the Birdweather GraphQL API (~5 pages)
const fetchAllStations = async (): Promise<GraphQLStationNode[]> => {
  const allNodes: GraphQLStationNode[] = [];
  let cursor: string | null = null;

  for (let page = 0; page < MAX_PAGES; page++) {
    // The period filter makes the server skip stations that have never had a detection
    const graphqlQuery = `query {
      stations(first: ${PAGE_SIZE}${cursor ? `, after: "${cursor}"` : ""
      }, period: {count: ${DETECTION_PERIOD_YEARS}, unit: "year"}) {
        pageInfo { hasNextPage endCursor }
        nodes { id name coords { lat lon } latestDetectionAt }
      }
    }`;

    const result: GraphQLStationsResponse = await fetchGraphQL(graphqlQuery);
    const stations = result.data?.stations;

    if (!stations) {
      throw new Error("Error: unexpected GraphQL response");
    }

    allNodes.push(...stations.nodes);
    console.log(`Fetched ${allNodes.length} stations`);

    if (!stations.pageInfo.hasNextPage || !stations.pageInfo.endCursor) {
      break;
    }

    cursor = stations.pageInfo.endCursor;
  }

  return allNodes;
};

// Compact tuple format to keep the file small. Stations without coordinates
// have location privacy enabled and can't be shown on a map, and ones that
// have never detected anything don't deserve a pin — neither has a query
// argument, so both are filtered here
const toMapStations = (nodes: GraphQLStationNode[]): MapStation[] => {
  const stations = nodes.flatMap<MapStation>((node) => {
    if (!node.coords || !node.latestDetectionAt) return [];

    const station: MapStation = [
      node.id,
      cleanStationName(node.name?.trim()) || `Station ${node.id}`,
      roundCoordinate(node.coords.lat),
      roundCoordinate(node.coords.lon),
    ];
    return [station];
  });

  // Birdweather returns stations in an unstable order. Sorting by id means a
  // regenerated file only differs where stations actually changed, which keeps
  // the git delta small (~12 KB per regeneration instead of ~130 KB)
  return stations.sort((a, b) => Number(a[0]) - Number(b[0]));
};

// One station per line, so a regenerated file is reviewable in a diff
const formatJson = ({ updatedAt, stations }: StationsMapData) =>
  `{\n  "updatedAt": ${JSON.stringify(updatedAt)},\n  "stations": [\n` +
  stations.map((station) => `    ${JSON.stringify(station)}`).join(",\n") +
  `\n  ]\n}\n`;

const formatConstant = (cacheVersion: string) =>
  `// Generated by "npm run update-stations" — do not edit by hand.\n` +
  `// The ?v= param busts the browser cache when the data is regenerated.\n` +
  `export const STATIONS_URL = "/data/stations.json?v=${cacheVersion}";\n`;

const run = async () => {
  const nodes = await fetchAllStations();
  const stations = toMapStations(nodes);

  if (!stations.length) {
    throw new Error("Error: no stations with coordinates were returned");
  }

  const updatedAt = new Date().toISOString();
  const cacheVersion = updatedAt.slice(0, 10).replace(/-/g, "");

  mkdirSync(DATA_DIRECTORY, { recursive: true });
  writeFileSync(DATA_FILE, formatJson({ updatedAt, stations }));
  writeFileSync(CONSTANT_FILE, formatConstant(cacheVersion));

  console.log(`Wrote ${stations.length} stations to ${DATA_FILE}`);
  console.log(`Wrote ${CONSTANT_FILE} (?v=${cacheVersion})`);
};

run();
